<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <Authors>Dante Karl Wackermann</Authors>
    <AssemblyName>LabelWhisper</AssemblyName>
    <AssemblyTitle>Label Whisper</AssemblyTitle>
    <RootNamespace>LabelWhisper</RootNamespace>
    <Version>3.1.0</Version>
    <NoWarn>1701;1702;IDE0063</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Remove="Assets\GEFORCE-BOLD.TTF" />
    <AvaloniaResource Remove="Assets\GEFORCE-LIGHT.TTF" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Extern\SumatraPDF-3.5.2-64.exe" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\GEFORCE-BOLD.TTF" />
    <EmbeddedResource Include="Assets\GEFORCE-LIGHT.TTF" />
    <EmbeddedResource Include="Extern\SumatraPDF-3.5.2-64.exe" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.8" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.2.8" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.8" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.8" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.8" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.2.8">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="QuestPDF" Version="2025.4.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.8" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.6" />
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
    <PackageReference Include="System.Management" Version="9.0.4" />
  </ItemGroup>


  <ItemGroup>
    <Reference Include="neXn.Lib">
      <HintPath>..\Libraries\neXn.Lib.dll</HintPath>
    </Reference>
    <Reference Include="neXn.Lib.ConfigurationHandler">
      <HintPath>..\Libraries\neXn.Lib.ConfigurationHandler.dll</HintPath>
    </Reference>
    <Reference Include="neXn.Ui">
      <HintPath>..\Libraries\neXn.Ui.dll</HintPath>
    </Reference>
    <Reference Include="neXn.Ui.Avalonia">
      <HintPath>..\Libraries\neXn.Ui.Avalonia.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
