<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <Authors>Dante Karl Wackermann</Authors>
    <AssemblyName>LabelPrinter</AssemblyName>
    <AssemblyTitle>Label Printer</AssemblyTitle>
    <RootNamespace>LabelPrinter</RootNamespace>
    <Version>3.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Remove="Assets\GEFORCE-BOLD.TTF" />
    <AvaloniaResource Remove="Assets\GEFORCE-LIGHT.TTF" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\GEFORCE-BOLD.TTF" />
    <EmbeddedResource Include="Assets\GEFORCE-LIGHT.TTF" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.6" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.6" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.6" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.6" />
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.2.6" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.7" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.5" />
  </ItemGroup>
</Project>
