; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Label Whisper"
#define MyAppVersion "3.2.2"
#define MyAppPublisher "Dante Wackermann"
#define MyAppURL "https://github.com/spreedated/"
#define MyAppExeName "LabelWhisper.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{69E4E413-4A0F-4485-89AA-A3948E2380F3}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=D:\labelprinter\LICENSE.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=LabelWhisper_{#MyAppVersion}_Setup
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\av_libglesv2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\LabelWhisper.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\libgcc_s_seh-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\libHarfBuzzSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\libSkiaSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\libstdc++-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\libwinpthread-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\neXn.Ui.Avalonia.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\qpdf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\QuestPdfSkia.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\zlib1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\LatoFont\OFL.txt"; DestDir: "{app}\LatoFont"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\LatoFont\Lato-Black.ttf"; DestDir: "{app}\LatoFont"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\LatoFont\Lato-BlackItalic.ttf"; DestDir: "{app}\LatoFont"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\LatoFont\Lato-Bold.ttf"; DestDir: "{app}\LatoFont"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\LatoFont\Lato-BoldItalic.ttf"; DestDir: "{app}\LatoFont"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\LatoFont\Lato-ExtraBold.ttf"; DestDir: "{app}\LatoFont"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\LatoFont\Lato-ExtraBoldItalic.ttf"; DestDir: "{app}\LatoFont"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\LatoFont\Lato-ExtraLight.ttf"; DestDir: "{app}\LatoFont"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\LatoFont\Lato-ExtraLightItalic.ttf"; DestDir: "{app}\LatoFont"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\LatoFont\Lato-Italic.ttf"; DestDir: "{app}\LatoFont"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\LatoFont\Lato-Light.ttf"; DestDir: "{app}\LatoFont"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\LatoFont\Lato-LightItalic.ttf"; DestDir: "{app}\LatoFont"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\LatoFont\Lato-Medium.ttf"; DestDir: "{app}\LatoFont"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\LatoFont\Lato-MediumItalic.ttf"; DestDir: "{app}\LatoFont"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\LatoFont\Lato-Regular.ttf"; DestDir: "{app}\LatoFont"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\LatoFont\Lato-SemiBold.ttf"; DestDir: "{app}\LatoFont"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\LatoFont\Lato-SemiBoldItalic.ttf"; DestDir: "{app}\LatoFont"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\LatoFont\Lato-Thin.ttf"; DestDir: "{app}\LatoFont"; Flags: ignoreversion
Source: "LabelWhisper\bin\Release\net9.0\publish\win-x64\LatoFont\Lato-ThinItalic.ttf"; DestDir: "{app}\LatoFont"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

